apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-eks-cluster
  region: ap-northeast-2
  version: "1.31"          # 생략 시 eksctl 기본값
iam:
  withOIDC: true           # IRSA 사용을 위해 필수
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
managedNodeGroups:
  - name: general
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
